### ISSUE TITLE
Good project but no docs

### ISSUE THREAD

**Issue by mysticaltech** [danwkennedy/arango-datasouce#76]
Hello, it seems like a very useful project to connect ArangoDB to an Apollo GraphQL server but there is absolutely no docs, please include. Thanks and keep up the good work!

**Comment by danwkennedy** [comment]
Hey, thanks for the request!

You're right that the docs are somewhat lacking. I pulled this layer out of a side project and so it's changing as needed. There are jsdocs but they're not helpful as a "Getting Started" guide. I'll add a basic readme with a description in a bit.

**Comment by mysticaltech** [comment]
Thanks, that would be awesome!

**Comment by danwkennedy** [comment]
Pushed some docs on how to get started.
